config/routes.rb
Rails.application.routes.draw do
  resources :job_postings
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'job_postings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]

  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting.all
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
  end

  # GET /job_postings/1/edit
  def edit
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_posting_params
      params.require(:job_posting).permit(:title, :keyword, :location, :headline_company, :description_company, :headline_offer, :description_offer, :headline_tasks, :description_tasks, :headline_team, :description_team)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/job_postings/_form.html.haml
= form_for @job_posting do |f|
  - if @job_posting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job_posting.errors.count, "error")} prohibited this job_posting from being saved:"
      %ul
        - @job_posting.errors.full_messages.each do |message|
          %li= message

  .row
    .column
      = f.label :title
      = f.text_field :title

  .row
    .column
      = f.label :keyword
      = f.text_field :keyword

  .row
    .column
      = f.label :location
      = f.text_field :location

  .row
    .column
      = f.label :headline_company
      = f.text_field :headline_company
    .column
      = f.label :description_company
      = f.hidden_field :description_company
      = content_tag 'trix-editor', '', input: :job_posting_description_company

  .row
    .column
      = f.label :headline_offer
      = f.text_field :headline_offer
    .column
      = f.label :description_offer
      = f.hidden_field :description_offer
      = content_tag 'trix-editor', '', input: :job_posting_description_offer

  .row
    .column
      = f.label :headline_tasks
      = f.text_field :headline_tasks
    .column
      = f.label :description_tasks
      = f.hidden_field :description_tasks
      = content_tag 'trix-editor', '', input: :job_posting_description_tasks

  .row
    .column
      = f.label :headline_team
      = f.text_field :headline_team
    .column
      = f.label :description_team
      = f.hidden_field :description_team
      = content_tag 'trix-editor', '', input: :job_posting_description_team

  .row
    .column
      = f.submit 'Speichern'
      = link_to 'Abbrechen', job_postings_path, class: 'button button-outline'

app/views/job_postings/edit.html.haml
.row
  .column
    %h1 Stellenanzeige bearbeiten

.row
  .column
    = render 'form'

app/views/job_postings/index.html.haml
.row
  .column
    %h1 Übersicht Stellenanzeigen

.row
  .column
    %table
      %thead
        %tr
          %th Titel
          %th Keyword
          %th Adresse
          %th
          %th
          %th

      %tbody
        - @job_postings.each do |job_posting|
          %tr
            %td= job_posting.title
            %td= job_posting.keyword
            %td= job_posting.location
            %td= link_to 'Preview', job_posting, target: '_blank'
            %td= link_to 'Bearbeiten', edit_job_posting_path(job_posting)
            %td= link_to 'Löschen', job_posting, method: :delete, data: { confirm: 'Are you sure?' }

.row
  .column
    = link_to 'Neuen Job anlegen', new_job_posting_path, class: 'button button-outline'

app/views/job_postings/new.html.haml
.row
  .column
    %h1 Neue Stellenanzeige

.row
  .column
    = render 'form'

app/views/job_postings/show.html.haml
.job_posting
  .job_posting__header
    .row.row-center
      .column.column-80
        %h1= @job_posting.title
      .column.column-20
        = link_to 'Jetzt bewerben', '#', id: 'cta_job_posting_apply', class: 'button'
    .row
      .column
        = @job_posting.location

  .job_posting__content
    .row
      .column
        %h2= @job_posting.headline_company
    .row
      .column
        = sanitize @job_posting.description_company

    .row
      .column
        %h2= @job_posting.headline_offer
    .row
      .column
        = sanitize @job_posting.description_offer

    .row
      .column
        %h2= @job_posting.headline_tasks
    .row
      .column
        = sanitize @job_posting.description_tasks

    .row
      .column
        %h2= @job_posting.headline_team
    .row
      .column
        = sanitize @job_posting.description_team

  .job_posting__footer
    .row.row-center
      .column.column-80
        %strong In wenigen Klicks ohne Anschreiben und Lebenslauf
      .column.column-20
        = link_to 'Jetzt bewerben', '#', id: 'cta_job_posting_apply', class: 'button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hero
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .container
      = yield